# Generated by Django 6.0.5 on 2026-06-03 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Agent"),
                            ("broker_firm", "Broker Firm"),
                            ("agency", "Agency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("license_expiry", models.DateField()),
                ("agent_code", models.CharField(max_length=50, unique=True)),
                ("specialization", models.CharField(blank=True, max_length=255)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("bank_code", models.CharField(blank=True, max_length=10)),
                ("total_policies", models.IntegerField(default=0)),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_clients", models.IntegerField(default=0)),
                ("active_policies", models.IntegerField(default=0)),
                ("lapsed_policies", models.IntegerField(default=0)),
                (
                    "total_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("claims_handled", models.IntegerField(default=0)),
                (
                    "customer_satisfaction_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Agent Performance",
            },
        ),
    ]
