# Generated by Django 6.0.5 on 2026-06-03 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentcommission",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="agentperformance",
            name="agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance",
                to="agents.agent",
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["agent_code"], name="agents_agen_agent_c_a24165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["status", "agent_type"], name="agents_agen_status_260be2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommission",
            index=models.Index(
                fields=["agent", "status"], name="agents_agen_agent_i_00c87a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommission",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="agents_agen_period__5ca83d_idx",
            ),
        ),
    ]
