# Generated by Django 6.0.5 on 2026-06-03 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        ("customers", "0001_initial"),
        ("policies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="policies.policy",
            ),
        ),
        migrations.AddField(
            model_name="claimassessment",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claim_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claimassessment",
            name="claim",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment",
                to="claims.claim",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="claims.claim",
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claimpayment",
            name="claim",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="claims.claim",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["claim_number"], name="claims_clai_claim_n_0cfa8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["policy", "status"], name="claims_clai_policy__5a2db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["customer", "status"], name="claims_clai_custome_343149_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["status", "priority"], name="claims_clai_status_3ce1a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimdocument",
            index=models.Index(
                fields=["claim", "document_type"], name="claims_clai_claim_i_182869_idx"
            ),
        ),
    ]
