# Generated by Django 6.0.5 on 2026-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='kra_pin_document',
            field=models.FileField(blank=True, null=True, upload_to='kra_pins/'),
        ),
    ]
