# Generated by Django 6.0.5 on 2026-06-03 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("motor", "Motor Insurance"),
                            ("travel", "Travel Insurance"),
                            ("health", "Health Insurance"),
                            ("fire", "Fire & General"),
                            ("liability", "Public Liability"),
                            ("marine", "Marine Insurance"),
                            ("accident", "Personal Accident"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "minimum_premium",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_premium",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product_name"],
                "indexes": [
                    models.Index(
                        fields=["product_type", "is_active"],
                        name="policies_in_product_de1a6d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("lapsed", "Lapsed"),
                            ("renewed", "Renewed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "premium_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "coverage_limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("policy_details", models.JSONField(blank=True, default=dict)),
                ("renewal_reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="agents.agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="policies.insuranceproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("payment_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mpesa", "Mpesa"),
                            ("credit_card", "Credit Card"),
                            ("insurance_company", "Insurance Company"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_number"], name="policies_po_policy__a03f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["customer", "status"], name="policies_po_custome_ec5ded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["agent", "status"], name="policies_po_agent_i_30c42b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["start_date", "end_date"], name="policies_po_start_d_1c1c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policypayment",
            index=models.Index(
                fields=["policy", "status"], name="policies_po_policy__cce84a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policypayment",
            index=models.Index(
                fields=["due_date", "status"], name="policies_po_due_dat_59bc79_idx"
            ),
        ),
    ]
