# Generated by Django 6.0.5 on 2026-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='category',
            field=models.CharField(choices=[('auto', 'Auto/Motor'), ('home', 'Home/Property'), ('health', 'Health'), ('life', 'Life'), ('travel', 'Travel'), ('business', 'Business'), ('disability', 'Disability')], default='auto', max_length=50),
        ),
        migrations.AddIndex(
            model_name='insuranceproduct',
            index=models.Index(fields=['category', 'is_active'], name='policies_in_categor_40c169_idx'),
        ),
    ]
